import Sidebar from '@/components/Sidebar'
import BottomNav from '@/components/BottomNav'
import { createClient } from '@/lib/supabase/server'

export default async function SearchPage({searchParams}:{searchParams?:{q?:string}}){
  const q=(searchParams?.q??'').trim(); const safeQ=q.replace(/[(),]/g,' '); const supabase=createClient()
  const {data:players}=q ? await supabase.from('profiles').select('username,display_name,city,country_code').or(`display_name.ilike.%${safeQ}%,username.ilike.%${safeQ}%,city.ilike.%${safeQ}%`).order('display_name',{ascending:true}).limit(30) : {data:[]}
  return <div className="min-h-screen bg-[#0B0F19] text-white grid-bg"><Sidebar/><main className="lg:pl-64 pb-20 lg:pb-0"><div className="max-w-6xl mx-auto px-4 md:px-6 py-8"><div className="text-xs tracking-[.3em] text-[#00F0FF] font-black">DISCOVERY</div><h1 className="text-4xl md:text-6xl font-black mt-2">Buscar</h1><form className="mt-6 flex gap-3"><input name="q" defaultValue={q} placeholder="Jugador, username o ciudad" className="flex-1 rounded-2xl bg-white/5 border border-white/10 px-5 py-4 outline-none"/><button className="rounded-2xl bg-[#00F0FF] text-black px-6 font-black">BUSCAR</button></form>{q&&<div className="mt-7 grid md:grid-cols-3 gap-4">{(players??[]).map((p:any)=><a href={`/u/${p.username}`} key={p.username} className="rounded-3xl border border-white/10 bg-[#141B2D] p-5 hover:border-cyan-300/30"><div className="text-xs text-[#FFD700]">#{'—'} · — PTS</div><div className="font-black text-xl mt-2">{p.display_name}</div><div className="text-sm text-white/40 mt-1">@{p.username} · {p.city||'Ubicación no indicada'}</div></a>)}{(players??[]).length===0&&<div className="md:col-span-3 rounded-3xl border border-white/10 bg-[#141B2D] p-8 text-center text-white/45">No encontramos jugadores con “{q}”.</div>}</div>}{!q&&<div className="mt-12 rounded-3xl border border-white/10 bg-[#141B2D] p-8 text-center text-white/45">Escribe un nombre, username o ciudad para descubrir jugadores.</div>}</div></main><BottomNav/></div>
}
