import Sidebar from '@/components/Sidebar'
import { createClient } from '@/lib/supabase/server'
import { ArrowDownLeft, ArrowUpRight, Receipt, WalletCards } from 'lucide-react'
import type { ReactNode } from 'react'
import PageHero from '@/components/PageHero'
import { getTranslations } from 'next-intl/server'
export const dynamic='force-dynamic'
export default async function FinancePage(){
 const supabase=await createClient(); const t=await getTranslations('Finance'); const {data:userData}=await supabase.auth.getUser(); const user=userData.user
 const {data:accountsData}=user?await supabase.from('finance_accounts').select('id,name,account_type,currency_code,is_active').eq('profile_id',user.id).order('name'): {data:[]}
 const {data:txData}=user?await supabase.from('finance_transactions').select('id,transaction_type,amount,currency_code,occurred_at,description,counterparty_name,status,source_type').eq('profile_id',user.id).order('occurred_at',{ascending:false}).limit(40):{data:[]}
 const {data:paymentsData}=user?await supabase.from('payment_records').select('id,booking_id,provider,amount,currency_code,status,paid_at,refunded_amount').eq('payer_profile_id',user.id).order('created_at',{ascending:false}).limit(20):{data:[]}
 const {data:invoicesData}=user?await supabase.from('finance_invoices').select('id,invoice_number,direction,counterparty_name,issue_date,due_date,total_amount,paid_amount,currency_code,status,source_type').eq('profile_id',user.id).order('issue_date',{ascending:false}).limit(30):{data:[]}
 const accounts = accountsData ?? []
 const tx = txData ?? []
 const payments = paymentsData ?? []
 const invoices = invoicesData ?? []
 const inflow=tx.filter((x)=>x.transaction_type==='income'||x.transaction_type==='credit').reduce((n,x)=>n+Number(x.amount||0),0)
 const outflow=tx.filter((x)=>x.transaction_type==='expense'||x.transaction_type==='debit').reduce((n,x)=>n+Number(x.amount||0),0)
 return <main className="min-h-screen bg-[#0A0A0C] text-white grid-bg"><Sidebar/><section className="lg:pl-64 p-6 lg:p-12 max-w-[1450px] mx-auto"><div className="mb-8"><PageHero><div className="text-[#D4AF37] text-xs font-black tracking-[.28em] uppercase">{t('tag')}</div><h1 className="text-4xl md:text-6xl font-display font-black tracking-wide mt-2">{t('title')}</h1><p className="text-white/50 mt-3 max-w-3xl">{t('subtitle')}</p></PageHero></div>
 <div className="grid md:grid-cols-3 gap-4"><Metric icon={<WalletCards/>} label={t('activeAccounts')} value={String(accounts.filter((x)=>x.is_active).length)}/><Metric icon={<ArrowDownLeft/>} label={t('registeredIncome')} value={inflow.toLocaleString('es-CO')}/><Metric icon={<ArrowUpRight/>} label={t('registeredExpenses')} value={outflow.toLocaleString('es-CO')}/></div>
 <div className="grid xl:grid-cols-3 gap-6 mt-6"><section className="rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#D4AF37] font-black tracking-widest">{t('paymentsTag')}</div><h2 className="text-2xl font-black mt-1">{t('paymentsTitle')}</h2></div><WalletCards className="text-[#D4AF37]"/></div>{payments.length===0?<Empty text={t('emptyPayments')}/>:<div className="mt-5 space-y-3">{payments.map((p)=><div key={p.id} className="rounded-2xl border border-white/10 p-4 flex justify-between"><div><div className="font-black">{p.provider||t('defaultProvider')}</div><div className="text-xs text-white/40 mt-1">{p.status} · {p.paid_at?new Date(p.paid_at).toLocaleString('es-CO'):t('pending')}</div></div><div className="text-right font-black">{Number(p.amount||0).toLocaleString('es-CO')} {p.currency_code||'COP'}</div></div>)}</div>}</section><section className="rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#D4AF37] font-black tracking-widest">{t('accountsTag')}</div><h2 className="text-2xl font-black mt-1">{t('accountsTitle')}</h2></div><span className="text-xs text-white/40">{accounts.length}</span></div>{accounts.length===0?<Empty text={t('emptyAccounts')}/>:<div className="mt-5 space-y-3">{accounts.map((a)=><div key={a.id} className="rounded-2xl border border-white/10 p-4 flex justify-between"><div><div className="font-black">{a.name}</div><div className="text-xs text-white/40 mt-1">{a.account_type}</div></div><div className="text-right font-black">{a.currency_code}</div></div>)}</div>}</section>
 <section className="rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#D4AF37] font-black tracking-widest">{t('invoicesTag')}</div><h2 className="text-2xl font-black mt-1">{t('invoicesTitle')}</h2></div><Receipt className="text-[#D4AF37]"/></div>{invoices.length===0?<Empty text={t('emptyInvoices')}/>:<div className="mt-5 space-y-3">{invoices.map((i)=><div key={i.id} className="rounded-2xl border border-white/10 p-4 flex justify-between"><div><div className="font-black">{i.invoice_number||t('defaultInvoice')}</div><div className="text-xs text-white/40 mt-1">{i.counterparty_name||t('defaultCounterparty')} · {i.status}</div></div><div className="text-right font-black">{Number(i.total_amount).toLocaleString('es-CO')} {i.currency_code}</div></div>)}</div>}</section></div>
 <section className="mt-6 rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#D4AF37] font-black tracking-widest">{t('ledgerTag')}</div><h2 className="text-2xl font-black mt-1">{t('ledgerTitle')}</h2></div><span className="text-xs text-white/40">{t('recordsCount',{count:tx.length})}</span></div>{tx.length===0?<Empty text={t('emptyLedger')}/>:<div className="mt-5 divide-y divide-white/5">{tx.map((t2)=><div key={t2.id} className="py-4 flex flex-wrap items-center justify-between gap-3"><div><div className="font-black">{t2.description||t2.transaction_type}</div><div className="text-xs text-white/40 mt-1">{t2.counterparty_name||'—'} · {t2.source_type||t('manual')} · {t2.status}</div></div><div className="text-right"><div className="font-black">{Number(t2.amount).toLocaleString('es-CO')} {t2.currency_code}</div><div className="text-xs text-white/35">{new Date(t2.occurred_at).toLocaleString('es-CO')}</div></div></div>)}</div>}</section>
 </section></main>
}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-3xl border border-white/10 bg-[#161616] p-5"><div className="text-[#D4AF37]">{icon}</div><div className="text-xs text-white/40 uppercase tracking-widest mt-3">{label}</div><div className="text-2xl font-black mt-1">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="mt-5 rounded-2xl border border-dashed border-white/10 p-8 text-white/45">{text}</div>}
