import Sidebar from '@/components/Sidebar'
import { createClient } from '@/lib/supabase/server'
import { ArrowDownLeft, ArrowUpRight, Receipt, WalletCards } from 'lucide-react'
import type { ReactNode } from 'react'
export const dynamic='force-dynamic'
export default async function FinancePage(){
 const supabase=createClient(); const {data:userData}=await supabase.auth.getUser(); const user=userData.user
 const {data:accounts=[]}=user?await supabase.from('finance_accounts').select('id,name,account_type,currency_code,is_active').eq('profile_id',user.id).order('name'): {data:[]}
 const {data:tx=[]}=user?await supabase.from('finance_transactions').select('id,transaction_type,amount,currency_code,occurred_at,description,counterparty_name,status,source_type').eq('profile_id',user.id).order('occurred_at',{ascending:false}).limit(40):{data:[]}
 const {data:payments=[]}=user?await supabase.from('payment_records').select('id,booking_id,provider,amount,currency_code,status,paid_at,refunded_amount').eq('payer_profile_id',user.id).order('created_at',{ascending:false}).limit(20):{data:[]}
 const {data:invoices=[]}=user?await supabase.from('finance_invoices').select('id,invoice_number,direction,counterparty_name,issue_date,due_date,total_amount,paid_amount,currency_code,status,source_type').eq('profile_id',user.id).order('issue_date',{ascending:false}).limit(30):{data:[]}
 const inflow=tx.filter((x:any)=>x.transaction_type==='income'||x.transaction_type==='credit').reduce((n,x)=>n+Number(x.amount||0),0)
 const outflow=tx.filter((x:any)=>x.transaction_type==='expense'||x.transaction_type==='debit').reduce((n,x)=>n+Number(x.amount||0),0)
 return <main className="min-h-screen bg-[#0B0F19] text-white grid-bg"><Sidebar/><section className="lg:pl-64 p-6 lg:p-12 max-w-[1450px] mx-auto"><div className="mb-8"><div className="text-[#00F0FF] text-xs font-black tracking-[.28em] uppercase">Dynasty Finance OS</div><h1 className="text-4xl md:text-6xl font-black mt-2">Finanzas avanzadas</h1><p className="text-white/50 mt-3 max-w-3xl">Cuentas, movimientos e invoices con trazabilidad de origen. Las operaciones sensibles siguen protegidas por RLS y contratos server-side.</p></div>
 <div className="grid md:grid-cols-3 gap-4"><Metric icon={<WalletCards/>} label="Cuentas activas" value={String(accounts.filter((x:any)=>x.is_active).length)}/><Metric icon={<ArrowDownLeft/>} label="Ingresos registrados" value={inflow.toLocaleString('es-CO')}/><Metric icon={<ArrowUpRight/>} label="Egresos registrados" value={outflow.toLocaleString('es-CO')}/></div>
 <div className="grid xl:grid-cols-3 gap-6 mt-6"><section className="rounded-3xl border border-white/10 bg-[#141B2D] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#FFD700] font-black tracking-widest">PAYMENTS</div><h2 className="text-2xl font-black mt-1">Pagos</h2></div><WalletCards className="text-[#00F0FF]"/></div>{payments.length===0?<Empty text="No hay pagos visibles todavía."/>:<div className="mt-5 space-y-3">{payments.map((p:any)=><div key={p.id} className="rounded-2xl border border-white/10 p-4 flex justify-between"><div><div className="font-black">{p.provider||'Proveedor'}</div><div className="text-xs text-white/40 mt-1">{p.status} · {p.paid_at?new Date(p.paid_at).toLocaleString('es-CO'):'Pendiente'}</div></div><div className="text-right font-black">{Number(p.amount||0).toLocaleString('es-CO')} {p.currency_code||'COP'}</div></div>)}</div>}</section><section className="rounded-3xl border border-white/10 bg-[#141B2D] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#FFD700] font-black tracking-widest">ACCOUNTS</div><h2 className="text-2xl font-black mt-1">Cuentas</h2></div><span className="text-xs text-white/40">{accounts.length}</span></div>{accounts.length===0?<Empty text="No hay cuentas financieras visibles todavía."/>:<div className="mt-5 space-y-3">{accounts.map((a:any)=><div key={a.id} className="rounded-2xl border border-white/10 p-4 flex justify-between"><div><div className="font-black">{a.name}</div><div className="text-xs text-white/40 mt-1">{a.account_type}</div></div><div className="text-right font-black">{a.currency_code}</div></div>)}</div>}</section>
 <section className="rounded-3xl border border-white/10 bg-[#141B2D] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#00F0FF] font-black tracking-widest">INVOICES</div><h2 className="text-2xl font-black mt-1">Invoices</h2></div><Receipt className="text-[#FFD700]"/></div>{invoices.length===0?<Empty text="No hay invoices visibles todavía."/>:<div className="mt-5 space-y-3">{invoices.map((i:any)=><div key={i.id} className="rounded-2xl border border-white/10 p-4 flex justify-between"><div><div className="font-black">{i.invoice_number||'Invoice'}</div><div className="text-xs text-white/40 mt-1">{i.counterparty_name||'Contraparte'} · {i.status}</div></div><div className="text-right font-black">{Number(i.total_amount).toLocaleString('es-CO')} {i.currency_code}</div></div>)}</div>}</section></div>
 <section className="mt-6 rounded-3xl border border-white/10 bg-[#141B2D] p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-[#00F0FF] font-black tracking-widest">LEDGER</div><h2 className="text-2xl font-black mt-1">Últimos movimientos</h2></div><span className="text-xs text-white/40">{tx.length} registros</span></div>{tx.length===0?<Empty text="No hay movimientos financieros visibles todavía."/>:<div className="mt-5 divide-y divide-white/5">{tx.map((t:any)=><div key={t.id} className="py-4 flex flex-wrap items-center justify-between gap-3"><div><div className="font-black">{t.description||t.transaction_type}</div><div className="text-xs text-white/40 mt-1">{t.counterparty_name||'—'} · {t.source_type||'manual'} · {t.status}</div></div><div className="text-right"><div className="font-black">{Number(t.amount).toLocaleString('es-CO')} {t.currency_code}</div><div className="text-xs text-white/35">{new Date(t.occurred_at).toLocaleString('es-CO')}</div></div></div>)}</div>}</section>
 </section></main>
}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><div className="text-[#00F0FF]">{icon}</div><div className="text-xs text-white/40 uppercase tracking-widest mt-3">{label}</div><div className="text-2xl font-black mt-1">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="mt-5 rounded-2xl border border-dashed border-white/10 p-8 text-white/45">{text}</div>}
