export const dynamic = 'force-dynamic'
import Sidebar from '@/components/Sidebar'; import BottomNav from '@/components/BottomNav'; import { createClient } from '@/lib/supabase/server'
import PageHero from '@/components/PageHero'
import { getTranslations } from 'next-intl/server'
export default async function Coaches(){
  const supabase=await createClient(); const t=await getTranslations('Coaches');
  const {data:coaches}=await supabase.from('provider_profiles').select('id,profile_id,provider_type,headline,bio,is_independent,accepts_online,accepts_in_person,default_currency,status').eq('status','active').eq('provider_type','coach').order('created_at',{ascending:false}).limit(60);
  const {data:services}=await supabase.from('provider_services').select('id,provider_id,title,description,service_mode,price,currency_code,status').eq('status','active').order('created_at',{ascending:false}).limit(60);
  return <div className="min-h-screen bg-[#0A0A0C] text-white grid-bg"><Sidebar/><main className="lg:pl-64 pb-20"><div className="max-w-6xl mx-auto px-4 md:px-6 py-8"><PageHero><div className="text-xs tracking-[.3em] text-[#D4AF37] font-black">COACH OS</div><h1 className="text-4xl md:text-6xl font-display font-black tracking-wide mt-2">{t('title')}</h1><p className="text-white/50 mt-3 max-w-3xl">{t('subtitle')}</p></PageHero><div className="grid lg:grid-cols-2 gap-5 mt-8"><div className="rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="text-xs text-[#D4AF37] font-black tracking-widest">{t('activeCoaches')}</div><div className="text-4xl font-display font-black tracking-wide mt-2">{(coaches??[]).length}</div>{(coaches??[]).length===0?<p className="text-white/45 mt-3">{t('noCoaches')}</p>:<div className="space-y-3 mt-5">{coaches?.slice(0,8).map((c)=><div key={c.id} className="rounded-2xl border border-white/10 p-4"><div className="font-black">{c.headline || t('defaultCoachName')}</div><div className="text-xs text-white/40 mt-1">{c.is_independent?t('independent'):t('affiliated')} · {c.accepts_in_person?t('inPerson'):''}{c.accepts_online?` · ${t('online')}`:''}</div></div>)}</div>}</div><div className="rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="text-xs text-[#D4AF37] font-black tracking-widest">{t('activeServices')}</div><div className="text-4xl font-display font-black tracking-wide mt-2">{(services??[]).length}</div>{(services??[]).length===0?<p className="text-white/45 mt-3">{t('noServices')}</p>:<div className="space-y-3 mt-5">{services?.slice(0,8).map((s)=><div key={s.id} className="rounded-2xl border border-white/10 p-4"><div className="font-black">{s.title}</div><div className="text-sm text-white/45 mt-1">{Number(s.price).toLocaleString('es-CO')} {s.currency_code} · {s.service_mode}</div></div>)}</div>}</div></div></div></main><BottomNav/></div>}
