import Link from 'next/link'
export const dynamic = 'force-dynamic'
import Sidebar from '@/components/Sidebar'; import BottomNav from '@/components/BottomNav'; import ChallengeCard from '@/components/ChallengeCard'; import SocialPostCard from '@/components/SocialPostCard'; import { Bell, Search, Zap, TrendingUp, Swords } from 'lucide-react'; import { createClient } from '@/lib/supabase/server'

type FeedRow = { id: string; author_profile_id: string; post_type: string; body: string; created_at: string; profiles: { username: string | null; display_name: string | null } | null }
type LiveParticipant = { challenge_id: string; profile_id: string; role: string; status: string; profile: { display_name: string | null } | null }

export default async function Home(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser()
 const [{data:profile},{data:feed},{data:liveChallenges},{data:primarySport}]=await Promise.all([
  user ? supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle() : Promise.resolve({data:null}),
  supabase.from('social_posts').select('id,author_profile_id,post_type,body,created_at,profiles!social_posts_author_profile_id_fkey(username,display_name)').order('created_at',{ascending:false}).limit(8).returns<FeedRow[]>(),
  supabase.from('challenges').select('id,title,status,scheduled_at,location_name,creator_id,sport_id').eq('status','open').gte('scheduled_at',new Date().toISOString()).order('scheduled_at').limit(4),
  user ? supabase.from('player_sports').select('sport_id').eq('profile_id',user.id).eq('is_primary',true).maybeSingle() : Promise.resolve({data:null}),
 ])
 const {data:myRanking}=user&&primarySport?.sport_id ? await supabase.from('sport_rankings').select('rating,rank,wins,losses,matches_played').eq('profile_id',user.id).eq('sport_id',primarySport.sport_id).maybeSingle() : {data:null}
 const liveIds=(liveChallenges??[]).map((c)=>c.id); const {data:liveParticipants}=liveIds.length?await supabase.from('challenge_participants').select('challenge_id,profile_id,role,status,profile:profiles!challenge_participants_profile_id_fkey(display_name)').in('challenge_id',liveIds).in('status',['accepted','invited']).returns<LiveParticipant[]>():{data:[]}; const liveMap=new Map<string,LiveParticipant[]>(); for(const p of liveParticipants??[]){const a=liveMap.get(p.challenge_id)??[];a.push(p);liveMap.set(p.challenge_id,a)}
 const postIds=(feed??[]).map((p)=>p.id); const {data:likes}=user&&postIds.length?await supabase.from('social_reactions').select('post_id').eq('profile_id',user.id).eq('reaction_type','like').in('post_id',postIds):{data:[]}
 const likedSet=new Set((likes??[]).map((x)=>x.post_id)); const postData=(feed??[]).map((p)=>({...p,user_id:p.author_profile_id,type:p.post_type,content:p.body,username:p.profiles?.username||'jugador',full_name:p.profiles?.display_name||'Jugador',liked_by_me:likedSet.has(p.id)}))
 return <div className="min-h-screen bg-[#0B0F19] grid-bg"><Sidebar/><main className="lg:pl-64 pb-20 lg:pb-0"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#0B0F19]/90 backdrop-blur"><div className="max-w-[1500px] mx-auto px-4 md:px-6 h-16 flex items-center gap-4"><div className="lg:hidden font-black">CHALLENGE<span className="text-[#00F0FF]"> DYNASTY</span></div><form action="/search" className="hidden md:flex items-center gap-2 flex-1 rounded-xl bg-white/5 px-3 py-2 max-w-md"><Search size={17} className="text-white/40"/><input name="q" className="bg-transparent outline-none w-full text-sm" placeholder="Buscar jugadores, retos o clubes..."/></form><div className="ml-auto flex items-center gap-2"><Link href="/challenge/new" className="hidden sm:flex rounded-xl bg-[#00F0FF] text-black px-4 py-2.5 text-sm font-black items-center gap-2"><Zap size={16}/> RETAR</Link><Link href="/notifications" className="rounded-xl bg-white/5 p-2.5"><Bell size={18}/></Link><Link href={user&&profile?.username?`/u/${profile.username}`:'/login'} className="h-9 w-9 rounded-full bg-gradient-to-br from-cyan-300 to-blue-600" aria-label="Mi perfil"/></div></div></header>
 <div className="max-w-[1500px] mx-auto px-4 md:px-6 py-7"><section className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#141B2D] via-[#101827] to-[#0B0F19] p-6 md:p-10 overflow-hidden relative"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative max-w-3xl"><div className="text-xs tracking-[.3em] text-[#00F0FF] font-bold">MULTI-SPORT · COMPETITIVE SOCIAL</div><h1 className="text-4xl md:text-6xl font-black tracking-tight mt-3">¿A QUIÉN VAS A <span className="text-[#00F0FF]">RETAR</span> HOY?</h1><p className="mt-4 text-white/60 text-base md:text-lg">Encuentra rival, partner o competencia. Juega, crea, sube y haz historia en cualquier deporte.</p><div className="flex flex-wrap gap-3 mt-7"><Link href="/sports" className="rounded-2xl border border-white/15 bg-white/5 px-5 py-3 font-bold">🌎 TODOS LOS DEPORTES</Link><Link href="/challenge/new" className="rounded-2xl bg-[#00F0FF] text-black px-5 py-3 font-black flex items-center gap-2"><Zap size={18}/> CREAR RETO</Link><Link href="/challenge/new?instant=1" className="rounded-2xl border border-white/15 bg-white/5 px-5 py-3 font-bold">⚡ RETO INSTANTÁNEO</Link></div></div></section>
 <div className="mt-6"><div className="rounded-2xl border border-white/10 bg-[#141B2D] p-5 flex items-center justify-between"><div><div className="font-black">Tu pasaporte empieza aquí.</div><p className="text-sm text-white/45 mt-1">Configura un deporte y empieza a construir tu ranking.</p></div><Link href="/onboarding" className="rounded-xl bg-[#00F0FF] text-black px-4 py-2 font-black">EMPEZAR</Link></div></div>
 <div className="grid xl:grid-cols-[minmax(0,1fr)_360px] gap-6 mt-7"><div className="space-y-6"><section><div className="flex items-center justify-between mb-3"><h2 className="font-black text-lg">🔴 RETOS EN VIVO</h2><Link href="/arena" className="text-xs text-white/50">Ver todos</Link></div><div className="grid md:grid-cols-2 gap-4">{(liveChallenges??[]).map((c)=>{const ps=liveMap.get(c.id)??[];const creator=ps.find(p=>p.role==='creator')?.profile;const rival=ps.find(p=>p.profile_id!==c.creator_id&&p.status!=='declined')?.profile;return <ChallengeCard key={c.id} id={c.id} title={`RETO ${c.status}`} a={creator?.display_name??'Jugador'} b={rival?.display_name??'Rival'} points={0} status={c.scheduled_at?new Date(c.scheduled_at).toLocaleString('es-CO',{hour:'2-digit',minute:'2-digit'}):'Por definir'} club={c.location_name??'Por definir'}/>})}</div>{(liveChallenges??[]).length===0&&<div className="rounded-2xl border border-white/10 bg-[#141B2D] p-6 text-white/45">No hay retos activos. Sé el primero en retar.</div>}</section>
 <section className="rounded-3xl border border-[#00F0FF]/20 bg-gradient-to-br from-[#00F0FF]/10 to-[#141B2D] p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="text-xs tracking-[.25em] text-[#00F0FF] font-black">🔥 SKILL CHALLENGES</div><h2 className="text-2xl font-black mt-2">Reta con un truco.</h2><p className="text-sm text-white/55 mt-1">Sube tu jugada, recibe votos y compite por Skill Points.</p></div><Link href="/tricks" className="rounded-xl bg-[#00F0FF] text-black px-4 py-3 text-sm font-black text-center">VER TRUCOS</Link></div></section>
 <section><div className="flex items-center justify-between mb-3"><h2 className="font-black text-lg">🔥 PARA TI</h2><Link href="/" className="text-xs text-white/40">Actualizado</Link></div><div className="space-y-4">{postData.map((p)=><SocialPostCard key={p.id} post={p} currentUserId={user?.id}/>)}</div>{postData.length===0&&<div className="rounded-2xl border border-white/10 bg-[#141B2D] p-6 text-white/45">Todavía no hay publicaciones. Los resultados oficiales aparecerán aquí automáticamente.</div>}</section></div>
 <aside className="space-y-5"><section className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><div className="flex items-center justify-between"><h3 className="font-black">🎯 TU PRÓXIMO PASO</h3><TrendingUp size={18} className="text-[#00E676]"/></div><p className="text-sm text-white/45 mt-3">Encuentra un rival compatible y pon tu ranking en juego.</p><Link href="/players" className="w-full mt-4 rounded-xl bg-[#00F0FF] text-black py-3 font-black block text-center">VER RIVALES</Link></section><section className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><h3 className="font-black">⚡ ACCIONES</h3><div className="grid grid-cols-2 gap-2 mt-4"><Link href="/challenge/new" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">RETAR</Link><Link href="/partners" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">PARTNER</Link><Link href="/ranking" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">RANKING</Link><Link href="/arena" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">ARENA</Link></div></section><section className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><div className="flex items-center gap-2"><Swords size={17} className="text-[#00F0FF]"/><h3 className="font-black">TU RANKING</h3></div><div className="text-4xl font-black text-[#FFD700] mt-3">{myRanking?.rank ? `#${myRanking.rank}` : '—'}</div><div className="text-sm text-white/45 mt-1">{myRanking?.rating != null ? `${Number(myRanking.rating).toFixed(0)} PTS · ${myRanking.wins ?? 0} victorias` : 'Configura un deporte y juega tu primer partido.'}</div></section></aside></div></div></main><BottomNav/></div>
}
