import Link from 'next/link'
export const dynamic = 'force-dynamic'
import Sidebar from '@/components/Sidebar'; import BottomNav from '@/components/BottomNav'; import ChallengeCard from '@/components/ChallengeCard'; import SocialPostCard from '@/components/SocialPostCard'; import { Bell, Search, Zap, TrendingUp, Swords } from 'lucide-react'; import { createClient } from '@/lib/supabase/server'; import { getTranslations, getLocale } from 'next-intl/server'

type FeedRow = { id: string; author_profile_id: string; post_type: string; body: string; created_at: string; profiles: { username: string | null; display_name: string | null } | null }
type LiveParticipant = { challenge_id: string; profile_id: string; role: string; status: string; profile: { display_name: string | null } | null }

export default async function Home(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser()
 const t=await getTranslations('Home'); const locale=await getLocale(); const dateLocale=locale==='en'?'en-US':'es-CO'
 const [{data:profile},{data:feed},{data:liveChallenges},{data:primarySport}]=await Promise.all([
  user ? supabase.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle() : Promise.resolve({data:null}),
  supabase.from('social_posts').select('id,author_profile_id,post_type,body,created_at,profiles!social_posts_author_profile_id_fkey(username,display_name)').order('created_at',{ascending:false}).limit(8).returns<FeedRow[]>(),
  supabase.from('challenges').select('id,title,status,scheduled_at,location_name,creator_id,sport_id').eq('status','open').gte('scheduled_at',new Date().toISOString()).order('scheduled_at').limit(4),
  user ? supabase.from('player_sports').select('sport_id').eq('profile_id',user.id).eq('is_primary',true).maybeSingle() : Promise.resolve({data:null}),
 ])
 const {data:myRanking}=user&&primarySport?.sport_id ? await supabase.from('sport_rankings').select('rating,rank,wins,losses,matches_played').eq('profile_id',user.id).eq('sport_id',primarySport.sport_id).maybeSingle() : {data:null}
 const liveIds=(liveChallenges??[]).map((c)=>c.id); const {data:liveParticipants}=liveIds.length?await supabase.from('challenge_participants').select('challenge_id,profile_id,role,status,profile:profiles!challenge_participants_profile_id_fkey(display_name)').in('challenge_id',liveIds).in('status',['accepted','invited']).returns<LiveParticipant[]>():{data:[]}; const liveMap=new Map<string,LiveParticipant[]>(); for(const p of liveParticipants??[]){const a=liveMap.get(p.challenge_id)??[];a.push(p);liveMap.set(p.challenge_id,a)}
 const postIds=(feed??[]).map((p)=>p.id); const {data:likes}=user&&postIds.length?await supabase.from('social_reactions').select('post_id').eq('profile_id',user.id).eq('reaction_type','like').in('post_id',postIds):{data:[]}
 const likedSet=new Set((likes??[]).map((x)=>x.post_id)); const postData=(feed??[]).map((p)=>({...p,user_id:p.author_profile_id,type:p.post_type,content:p.body,username:p.profiles?.username||t('defaultUsername'),full_name:p.profiles?.display_name||t('defaultDisplayName'),liked_by_me:likedSet.has(p.id)}))
 return <div className="min-h-screen bg-[#0A0A0C] grid-bg"><Sidebar/><main className="lg:pl-64 pb-20 lg:pb-0"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#0A0A0C]/90 backdrop-blur"><div className="max-w-[1500px] mx-auto px-4 md:px-6 h-16 flex items-center gap-4"><div className="lg:hidden font-black">CHALLENGE<span className="text-[#D4AF37]"> DYNASTY</span></div><form action="/search" className="hidden md:flex items-center gap-2 flex-1 rounded-xl bg-white/5 px-3 py-2 max-w-md"><Search size={17} className="text-white/40"/><input name="q" className="bg-transparent outline-none w-full text-sm" placeholder={t('searchPlaceholder')}/></form><div className="ml-auto flex items-center gap-2"><Link href="/challenge/new" className="hidden sm:flex rounded-xl bg-[#D4AF37] text-black px-4 py-2.5 text-sm font-black items-center gap-2"><Zap size={16}/> {t('createChallenge')}</Link><Link href="/notifications" className="rounded-xl bg-white/5 p-2.5"><Bell size={18}/></Link><Link href={user&&profile?.username?`/u/${profile.username}`:'/login'} className="h-9 w-9 rounded-full bg-gradient-to-br from-gold-300 to-gold-600" aria-label={t('myProfile')}/></div></div></header>
 <div className="max-w-[1500px] mx-auto px-4 md:px-6 py-7"><section className="rounded-3xl border border-[#D4AF37]/20 bg-gradient-to-br from-[#1B1A12] via-[#161616] to-[#0A0A0C] p-6 md:p-10 overflow-hidden relative"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-gold-400/10 blur-3xl"/><img src="/dynasty-badge.png" alt="" className="hidden md:block absolute right-8 top-1/2 -translate-y-1/2 w-56 h-56 object-contain opacity-25 pointer-events-none select-none" /><div className="relative max-w-3xl"><div className="text-xs tracking-[.3em] text-[#D4AF37] font-bold">{t('kicker')}</div><h1 className="text-4xl md:text-6xl font-display font-black tracking-wide tracking-tight mt-3">{t('heroPre')} <span className="text-[#D4AF37]">{t('heroHighlight')}</span> {t('heroPost')}</h1><p className="mt-4 text-white/60 text-base md:text-lg">{t('heroSubtitle')}</p><div className="flex flex-wrap gap-3 mt-7"><Link href="/sports" className="rounded-2xl border border-white/15 bg-white/5 px-5 py-3 font-bold">{t('allSports')}</Link><Link href="/challenge/new" className="rounded-2xl bg-[#D4AF37] text-black px-5 py-3 font-black flex items-center gap-2"><Zap size={18}/> {t('createChallengeBtn')}</Link><Link href="/challenge/new?instant=1" className="rounded-2xl border border-white/15 bg-white/5 px-5 py-3 font-bold">{t('instantChallenge')}</Link></div></div></section>
 <div className="mt-6"><div className="rounded-2xl border border-white/10 bg-[#161616] p-5 flex items-center justify-between"><div><div className="font-black">{t('passportTitle')}</div><p className="text-sm text-white/45 mt-1">{t('passportBody')}</p></div><Link href="/onboarding" className="rounded-xl bg-[#D4AF37] text-black px-4 py-2 font-black">{t('getStarted')}</Link></div></div>
 <div className="grid xl:grid-cols-[minmax(0,1fr)_360px] gap-6 mt-7"><div className="space-y-6"><section><div className="flex items-center justify-between mb-3"><h2 className="font-black text-lg">{t('liveChallengesTitle')}</h2><Link href="/arena" className="text-xs text-white/50">{t('seeAll')}</Link></div><div className="grid md:grid-cols-2 gap-4">{(liveChallenges??[]).map((c)=>{const ps=liveMap.get(c.id)??[];const creator=ps.find(p=>p.role==='creator')?.profile;const rival=ps.find(p=>p.profile_id!==c.creator_id&&p.status!=='declined')?.profile;return <ChallengeCard key={c.id} id={c.id} title={`${t('challengeLabel')} ${c.status}`} a={creator?.display_name??t('defaultPlayer')} b={rival?.display_name??t('defaultRival')} points={0} status={c.scheduled_at?new Date(c.scheduled_at).toLocaleString(dateLocale,{hour:'2-digit',minute:'2-digit'}):t('tbd')} club={c.location_name??t('tbd')}/>})}</div>{(liveChallenges??[]).length===0&&<div className="rounded-2xl border border-white/10 bg-[#161616] p-6 text-white/45">{t('noActiveChallenges')}</div>}</section>
 <section className="rounded-3xl border border-[#D4AF37]/20 bg-gradient-to-br from-[#D4AF37]/10 to-[#161616] p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="text-xs tracking-[.25em] text-[#D4AF37] font-black">{t('skillChallengesKicker')}</div><h2 className="text-2xl font-black mt-2">{t('skillChallengesTitle')}</h2><p className="text-sm text-white/55 mt-1">{t('skillChallengesBody')}</p></div><Link href="/tricks" className="rounded-xl bg-[#D4AF37] text-black px-4 py-3 text-sm font-black text-center">{t('viewTricks')}</Link></div></section>
 <section><div className="flex items-center justify-between mb-3"><h2 className="font-black text-lg">{t('forYouTitle')}</h2><Link href="/" className="text-xs text-white/40">{t('updated')}</Link></div><div className="space-y-4">{postData.map((p)=><SocialPostCard key={p.id} post={p} currentUserId={user?.id}/>)}</div>{postData.length===0&&<div className="rounded-2xl border border-white/10 bg-[#161616] p-6 text-white/45">{t('noPosts')}</div>}</section></div>
 <aside className="space-y-5"><section className="rounded-3xl border border-white/10 bg-[#161616] p-5"><div className="flex items-center justify-between"><h3 className="font-black">{t('nextStepTitle')}</h3><TrendingUp size={18} className="text-[#00E676]"/></div><p className="text-sm text-white/45 mt-3">{t('nextStepBody')}</p><Link href="/players" className="w-full mt-4 rounded-xl bg-[#D4AF37] text-black py-3 font-black block text-center">{t('viewRivals')}</Link></section><section className="rounded-3xl border border-white/10 bg-[#161616] p-5"><h3 className="font-black">{t('actionsTitle')}</h3><div className="grid grid-cols-2 gap-2 mt-4"><Link href="/challenge/new" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">{t('actionChallenge')}</Link><Link href="/partners" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">{t('actionPartner')}</Link><Link href="/ranking" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">{t('actionRanking')}</Link><Link href="/arena" className="rounded-xl bg-white/5 p-3 text-sm font-bold text-center">{t('actionArena')}</Link></div></section><section className="rounded-3xl border border-white/10 bg-[#161616] p-5"><div className="flex items-center gap-2"><Swords size={17} className="text-[#D4AF37]"/><h3 className="font-black">{t('myRankingTitle')}</h3></div><div className="text-4xl font-display font-black tracking-wide text-[#D4AF37] mt-3">{myRanking?.rank ? `#${myRanking.rank}` : '—'}</div><div className="text-sm text-white/45 mt-1">{myRanking?.rating != null ? t('rankingStats',{points:Number(myRanking.rating).toFixed(0),wins:myRanking.wins ?? 0}) : t('rankingEmpty')}</div></section></aside></div></div></main><BottomNav/></div>
}
