'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createSkillChallenge } from '@/app/actions/skills'
export default function CreateSkillChallengeForm({sports}:{sports:{id:string;name:string;icon:string|null}[]}){
 const router=useRouter(); const [sportId,setSportId]=useState(sports[0]?.id??''); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [category,setCategory]=useState('PRECISIÓN'); const [difficulty,setDifficulty]=useState<'BEGINNER'|'INTERMEDIATE'|'ADVANCED'|'PRO'|'ELITE'>('INTERMEDIATE'); const [points,setPoints]=useState(100); const [votes,setVotes]=useState(20); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const id=await createSkillChallenge({sportId,title,description,category,difficulty,points,targetVotes:votes});router.push(`/tricks/${id}`)}catch(e){setError(e instanceof Error?e.message:'No se pudo crear')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="mt-7 rounded-3xl border border-white/10 bg-[#141B2D] p-6 space-y-4"><select value={sportId} onChange={e=>setSportId(e.target.value)} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3">{sports.map(s=><option key={s.id} value={s.id}>{s.icon} {s.name}</option>)}</select><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nombre del challenge" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Qué tiene que conseguir el participante" className="w-full min-h-28 rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><div className="grid md:grid-cols-3 gap-3"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Categoría" className="rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><select value={difficulty} onChange={e=>setDifficulty(e.target.value as any)} className="rounded-xl bg-white/5 border border-white/10 px-4 py-3"><option>BEGINNER</option><option>INTERMEDIATE</option><option>ADVANCED</option><option>PRO</option><option>ELITE</option></select><input type="number" min="0" max="5000" value={points} onChange={e=>setPoints(Number(e.target.value))} className="rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div><input type="number" min="1" max="10000" value={votes} onChange={e=>setVotes(Number(e.target.value))} placeholder="Votos objetivo" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/>{error&&<div className="rounded-xl bg-red-500/10 border border-red-400/20 p-3 text-sm text-red-200">{error}</div>}<button disabled={busy||!sportId} className="w-full rounded-2xl bg-[#00F0FF] text-black py-4 font-black">{busy?'PUBLICANDO...':'PUBLICAR CHALLENGE'}</button></form>
}
