'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createSkillChallenge } from '@/app/actions/skills'
import { useTranslations } from 'next-intl'
export default function CreateSkillChallengeForm({sports}:{sports:{id:string;name:string;icon:string|null}[]}){
 const t=useTranslations('Tricks')
 const router=useRouter(); const [sportId,setSportId]=useState(sports[0]?.id??''); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [category,setCategory]=useState('PRECISIÓN'); const [difficulty,setDifficulty]=useState<'BEGINNER'|'INTERMEDIATE'|'ADVANCED'|'PRO'|'ELITE'>('INTERMEDIATE'); const [points,setPoints]=useState(100); const [votes,setVotes]=useState(20); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const res=await createSkillChallenge({sportId,title,description,category,difficulty,points,targetVotes:votes});if(!res.ok){setError(res.error||t('errCreateFailed'));setBusy(false);return}router.push(`/tricks/${res.data}`)}catch{setError(t('errCreateFailed'));setBusy(false)}}
 return <form onSubmit={submit} className="mt-7 card-fut-plain border border-white/10 bg-[#141416] p-6 space-y-4"><select value={sportId} onChange={e=>setSportId(e.target.value)} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3">{sports.map(s=><option key={s.id} value={s.id}>{s.icon} {s.name}</option>)}</select><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder={t('namePlaceholder')} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={t('descPlaceholder')} className="w-full min-h-28 rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><div className="grid md:grid-cols-3 gap-3"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder={t('categoryPlaceholder')} className="rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><select value={difficulty} onChange={e=>setDifficulty(e.target.value as typeof difficulty)} className="rounded-xl bg-white/5 border border-white/10 px-4 py-3"><option value="BEGINNER">{t('difficulty.BEGINNER')}</option><option value="INTERMEDIATE">{t('difficulty.INTERMEDIATE')}</option><option value="ADVANCED">{t('difficulty.ADVANCED')}</option><option value="PRO">{t('difficulty.PRO')}</option><option value="ELITE">{t('difficulty.ELITE')}</option></select><input type="number" min="0" max="5000" value={points} onChange={e=>setPoints(Number(e.target.value))} className="rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div><input type="number" min="1" max="10000" value={votes} onChange={e=>setVotes(Number(e.target.value))} placeholder={t('targetVotesPlaceholder')} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/>{error&&<div className="rounded-xl bg-red-500/10 border border-red-400/20 p-3 text-sm text-red-200">{error}</div>}<button disabled={busy||!sportId} className="w-full rounded-2xl bg-[#D4AF37] text-black py-4 font-black">{busy?t('publishing'):t('publishBtn')}</button></form>
}
