'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createChallenge } from '@/app/actions/challenges'

type Sport={id:string;name:string;slug:string;icon:string|null}
type Player={id:string;username:string;display_name:string;city:string|null}

export default function NewChallengeForm({sports,players,initialPlayerId,initialSportId}:{sports:Sport[];players:Player[];initialPlayerId?:string;initialSportId?:string}){
 const router=useRouter(); const [challengedId,setChallengedId]=useState(initialPlayerId ?? ''); const [sportId,setSportId]=useState(initialSportId ?? sports[0]?.id??''); const [date,setDate]=useState(''); const minDate=useMemo(()=>{const d=new Date(Date.now()+2*60*60*1000); return d.toISOString().slice(0,16)},[]); const [points,setPoints]=useState('100'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 const filteredPlayers = useMemo(() => players.filter(p => p.id !== undefined), [players])
 async function submit(e:React.FormEvent){e.preventDefault();setError(''); const parsedDate=new Date(date); const numericPoints=Number(points); if(Number.isNaN(parsedDate.getTime())){setError('Selecciona una fecha válida.');return} if(parsedDate.getTime()<Date.now()+2*60*60*1000){setError('El reto debe programarse con al menos 2 horas de anticipación.');return} if(numericPoints<1||numericPoints>5000){setError('Los puntos deben estar entre 1 y 5000.');return} setBusy(true);try{const id=await createChallenge({challengedId,sportId,matchDate:parsedDate.toISOString(),points:numericPoints});router.push(`/challenge/${id}`)}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el reto')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="mt-7 rounded-3xl border border-white/10 bg-[#141B2D] p-6 space-y-5"><div><label className="text-xs text-white/45">DEPORTE</label><select value={sportId} onChange={e=>setSportId(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3">{sports.map(s=><option key={s.id} value={s.id}>{s.icon} {s.name}</option>)}</select></div><div><label className="text-xs text-white/45">RIVAL</label><select value={challengedId} onChange={e=>setChallengedId(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"><option value="">Selecciona un rival</option>{filteredPlayers.map(p=><option key={p.id} value={p.id}>{p.display_name} @{p.username}{p.city?` · ${p.city}`:''}</option>)}</select></div><div className="grid md:grid-cols-2 gap-4"><div><label className="text-xs text-white/45">FECHA Y HORA</label><input type="datetime-local" min={minDate} value={date} onChange={e=>setDate(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div><div><label className="text-xs text-white/45">PUNTOS EN JUEGO</label><input type="number" min="1" max="5000" value={points} onChange={e=>setPoints(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div></div>{error&&<div className="rounded-xl bg-red-500/10 border border-red-400/20 p-3 text-sm text-red-200">{error}</div>}<button disabled={busy} className="w-full rounded-2xl bg-[#00F0FF] text-black py-4 font-black">{busy?'ENVIANDO...':'⚡ ENVIAR RETO'}</button></form>
}
