'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createChallenge } from '@/app/actions/challenges'
import { useTranslations } from 'next-intl'

type Sport={id:string;name:string;slug:string;icon:string|null}
type Player={id:string;username:string;display_name:string;city:string|null}

export default function NewChallengeForm({sports,players,initialPlayerId,initialSportId}:{sports:Sport[];players:Player[];initialPlayerId?:string;initialSportId?:string}){
 const t=useTranslations('Challenge')
 const router=useRouter(); const [challengedId,setChallengedId]=useState(initialPlayerId ?? ''); const [sportId,setSportId]=useState(initialSportId ?? sports[0]?.id??''); const [date,setDate]=useState(''); const [minDate]=useState(()=>{const d=new Date(Date.now()+2*60*60*1000); return new Date(d.getTime()-d.getTimezoneOffset()*60*1000).toISOString().slice(0,16)}); const [points,setPoints]=useState('100'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 const filteredPlayers = useMemo(() => players.filter(p => p.id !== undefined), [players])
 async function submit(e:React.FormEvent){e.preventDefault();setError(''); const parsedDate=new Date(date); const numericPoints=Number(points); if(Number.isNaN(parsedDate.getTime())){setError(t('errInvalidDate'));return} if(parsedDate.getTime()<Date.now()+2*60*60*1000){setError(t('errMinAdvance'));return} if(numericPoints<1||numericPoints>5000){setError(t('errPointsRange'));return} setBusy(true);try{const id=await createChallenge({challengedId,sportId,matchDate:parsedDate.toISOString(),points:numericPoints});router.push(`/challenge/${id}`)}catch(e){setError(e instanceof Error?e.message:t('errCreateFailed'))}finally{setBusy(false)}}
 return <form onSubmit={submit} className="mt-7 rounded-3xl border border-white/10 bg-[#161616] p-6 space-y-5"><div><label className="text-xs text-white/45">{t('sportLabel')}</label><select value={sportId} onChange={e=>setSportId(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3">{sports.map(s=><option key={s.id} value={s.id}>{s.icon} {s.name}</option>)}</select></div><div><label className="text-xs text-white/45">{t('rivalLabel')}</label><select value={challengedId} onChange={e=>setChallengedId(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"><option value="">{t('selectRival')}</option>{filteredPlayers.map(p=><option key={p.id} value={p.id}>{p.display_name} @{p.username}{p.city?` · ${p.city}`:''}</option>)}</select></div><div className="grid md:grid-cols-2 gap-4"><div><label className="text-xs text-white/45">{t('dateTimeLabel')}</label><input type="datetime-local" min={minDate} value={date} onChange={e=>setDate(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div><div><label className="text-xs text-white/45">{t('pointsLabel')}</label><input type="number" min="1" max="5000" value={points} onChange={e=>setPoints(e.target.value)} required className="mt-2 w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div></div>{error&&<div className="rounded-xl bg-red-500/10 border border-red-400/20 p-3 text-sm text-red-200">{error}</div>}<button disabled={busy} className="w-full rounded-2xl bg-[#D4AF37] text-black py-4 font-black">{busy?t('sending'):t('sendChallenge')}</button></form>
}
