'use client'
import { useState } from 'react'
import { updateProfile, updateProfileSport } from '@/app/actions/profile'

type Sport={id:string;name:string;icon:string|null}
type PS={sport_id:string;skill_level:string|null;is_primary:boolean}

export default function ProfileSettingsForm({profile,sports,profileSports}:{profile:{display_name?:string|null;username?:string|null;city?:string|null;country_code?:string|null}|null;sports:Sport[];profileSports:PS[]}) {
  const [fullName,setFullName]=useState(profile?.display_name??''); const [username,setUsername]=useState(profile?.username??''); const [city,setCity]=useState(profile?.city??''); const [country,setCountry]=useState(profile?.country_code??'CO'); const [sportId,setSportId]=useState(sports[0]?.id??profileSports[0]?.sport_id??''); const [level,setLevel]=useState(profileSports.find(x=>x.sport_id===sportId)?.skill_level??''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
  async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');try{await updateProfile({fullName,username,city,country});setMsg('Perfil actualizado.')}catch(e){setMsg(e instanceof Error?e.message:'No se pudo actualizar')}finally{setBusy(false)}}
  async function saveSport(){setBusy(true);setMsg('');try{await updateProfileSport({sportId,skillLevel:level,isPrimary:true});setMsg('Deporte actualizado.')}catch(e){setMsg(e instanceof Error?e.message:'No se pudo actualizar')}finally{setBusy(false)}}
  return <div className="grid lg:grid-cols-2 gap-5 mt-7"><form onSubmit={saveProfile} className="rounded-3xl border border-white/10 bg-[#141B2D] p-6 space-y-4"><h2 className="font-black text-xl">Identidad</h2><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Nombre" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="username" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><div className="grid grid-cols-2 gap-3"><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ciudad" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/><input value={country} onChange={e=>setCountry(e.target.value.toUpperCase().slice(0,2))} placeholder="CO" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"/></div><div className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm text-white/45">Club: próximamente, cuando conectemos el modelo oficial de membresías de clubes.</div><button disabled={busy} className="w-full rounded-xl bg-[#00F0FF] text-black py-3 font-black">{busy?'GUARDANDO...':'GUARDAR PERFIL'}</button></form><section className="rounded-3xl border border-white/10 bg-[#141B2D] p-6 space-y-4"><h2 className="font-black text-xl">Pasaporte deportivo</h2><select value={sportId} onChange={e=>{setSportId(e.target.value);setLevel(profileSports.find(x=>x.sport_id===e.target.value)?.skill_level??'')}} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3">{sports.map(s=><option key={s.id} value={s.id}>{s.icon} {s.name}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value)} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3"><option value="">Selecciona nivel</option><option>BEGINNER</option><option>INTERMEDIATE</option><option>ADVANCED</option><option>PRO</option><option>ELITE</option></select><button type="button" disabled={busy || !sportId} onClick={saveSport} className="w-full rounded-xl bg-white text-black py-3 font-black">GUARDAR DEPORTE PRINCIPAL</button><div className="text-xs text-white/35">Puedes añadir más deportes desde esta misma lógica; el principal es el que alimenta el descubrimiento por defecto.</div></section>{msg&&<div className="lg:col-span-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm">{msg}</div>}</div>
}
