'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowRight, Trash2 } from 'lucide-react'
import { toSafeMessage } from '@/lib/safe-error'
export default function ShopCartClient({cart,items,products}:{cart:{id:string};items:Array<{id:string;quantity:number;unit_price?:number;shop_products?:{title:string}|null;shop_product_variants?:{title:string|null;sku:string|null;price:number}|null}>;products:Array<{id:string}>}){
 const router=useRouter(); const supabase=createClient(); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState<string|null>(null); const [shipping,setShipping]=useState({full_name:'',phone:'',address:'',city:'',notes:''})
 const total=items.reduce((a,i)=>a+Number(i.shop_product_variants?.price||i.unit_price||0)*Number(i.quantity||0),0)
 async function remove(id:string){setBusy(true);setMsg(null);const {error}=await supabase.from('shop_cart_items').delete().eq('id',id);setMsg(error?toSafeMessage(error,'shopCart.remove'):'Ítem eliminado.');setBusy(false)}
 async function checkout(){setBusy(true);setMsg(null);const {data,error}=await supabase.rpc('checkout_shop_cart',{p_shipping_data:shipping}); if(error) setMsg(toSafeMessage(error,'shopCart.checkout')); else router.push('/shop/orders?order='+encodeURIComponent(data.id)); setBusy(false)}
 return <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-6"><section className="rounded-3xl border border-white/10 bg-[#161616] p-6"><div className="flex items-center justify-between"><h1 className="text-3xl font-display font-black tracking-wide">Tu carrito</h1><span className="text-xs text-white/40">{items.length} líneas</span></div><div className="mt-5 space-y-3">{items.map(i=><div key={i.id} className="rounded-2xl border border-white/10 p-4 flex items-center gap-4"><div className="w-16 h-16 rounded-xl bg-white/[.04] grid place-items-center text-white/15 font-black">D</div><div className="flex-1"><div className="font-black">{i.shop_products?.title||'Producto Dynasty'}</div><div className="text-sm text-white/45">{i.shop_product_variants?.title||i.shop_product_variants?.sku||'Variante'} · x{i.quantity}</div></div><div className="font-black">{(Number(i.shop_product_variants?.price||0)*Number(i.quantity||0)).toLocaleString('es-CO')} COP</div><button disabled={busy} onClick={()=>remove(i.id)} className="p-2 rounded-xl bg-red-400/10 text-red-200"><Trash2 size={15}/></button></div>)}{items.length===0&&<div className="p-10 text-center text-white/40">Tu carrito está vacío. <Link href="/shop" className="text-[#D4AF37] font-bold">Explorar Shop</Link></div>}</div></section><aside className="rounded-3xl border border-white/10 bg-[#161616] p-6"><h2 className="text-2xl font-display font-black tracking-wide">Checkout</h2><div className="space-y-2 mt-4">{([['full_name','Nombre completo'],['phone','Teléfono'],['address','Dirección'],['city','Ciudad'],['notes','Notas']] as const).map(([k,l])=><input key={k} value={shipping[k]} onChange={e=>setShipping(s=>({...s,[k]:e.target.value}))} className="w-full bg-[#0A0A0C] border border-white/10 rounded-xl px-3 py-3 text-sm" placeholder={l}/>)}</div><div className="border-t border-white/10 mt-5 pt-5 flex justify-between text-xl font-black"><span>Total</span><span>{total.toLocaleString('es-CO')} COP</span></div><button disabled={busy||items.length===0} onClick={checkout} className="mt-4 w-full rounded-xl bg-[#D4AF37] text-black font-black py-3 inline-flex justify-center items-center gap-2">{busy?'PROCESANDO…':'CONFIRMAR PEDIDO'}<ArrowRight size={17}/></button>{msg&&<div className="mt-3 text-sm text-white/60">{msg}</div>}</aside></div>
}
