'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ShoppingBag, Check, ArrowLeft } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { toSafeMessage } from '@/lib/safe-error'
import { useTranslations } from 'next-intl'

type Variant={id:string;sku:string|null;title:string|null;price:number;attributes:Record<string, string|number|boolean|null>|null}
export default function ShopProductClient({product,variants}:{product:{id:string;product_type:string;title:string;description:string|null;base_price:number;currency_code:string};variants:Variant[]}){
 const t=useTranslations('Shop')
 const supabase=createClient(); const [variantId,setVariantId]=useState(variants[0]?.id||''); const [qty,setQty]=useState(1); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState<string|null>(null)
 const variant=variants.find(v=>v.id===variantId)
 async function add(){ if(!variantId) return setMsg(t('selectVariant')); setBusy(true);setMsg(null); const {error}=await supabase.rpc('upsert_shop_cart_item',{p_product_id:product.id,p_variant_id:variantId,p_quantity:qty}); setMsg(error?toSafeMessage(error,'shop.addToCart'):t('addedToCart')); setBusy(false) }
 return <div className="max-w-6xl mx-auto"><Link href="/shop" className="inline-flex items-center gap-2 text-white/50 hover:text-white text-sm"><ArrowLeft size={15}/> {t('backToShop')}</Link><div className="grid lg:grid-cols-2 gap-8 mt-6"><div className="rounded-[2rem] border border-[#D4AF37]/20 bg-gradient-to-br from-[#1B1A12] via-[#161616] to-[#0A0A0C] aspect-square grid place-items-center p-10"><img src="/dynasty-badge.png" alt="Challenge Dynasty" className="w-2/3 h-2/3 object-contain opacity-70"/></div><section className="rounded-[2rem] border border-white/10 bg-[#161616] p-7"><div className="text-xs tracking-[.25em] text-[#D4AF37] font-black uppercase">{product.product_type}</div><h1 className="text-4xl md:text-5xl font-display font-black tracking-wide mt-2">{product.title}</h1><p className="text-white/55 mt-4 leading-7">{product.description||t('defaultDescription')}</p><div className="mt-7 text-3xl font-display font-black tracking-wide">{Number(variant?.price??product.base_price).toLocaleString('es-CO')} {product.currency_code}</div><div className="mt-7"><div className="text-xs uppercase tracking-widest text-white/40 mb-2">{t('variant')}</div><div className="grid sm:grid-cols-2 gap-2">{variants.map(v=><button key={v.id} onClick={()=>setVariantId(v.id)} className={`text-left rounded-xl border p-3 ${variantId===v.id?'border-[#D4AF37] bg-[#D4AF37]/10':'border-white/10 bg-white/[.02]'}`}><div className="font-bold">{v.title||v.sku||t('variant')}</div><div className="text-xs text-white/35 mt-1">{v.sku||t('noSku')}</div></button>)}</div></div><div className="flex gap-3 mt-5"><input value={qty} onChange={e=>setQty(Math.max(1,Math.min(20,Number(e.target.value)||1)))} className="w-24 bg-[#0A0A0C] border border-white/10 rounded-xl px-4" type="number" min="1" max="20"/><button disabled={busy||!variantId} onClick={add} className="flex-1 rounded-xl bg-[#D4AF37] text-black font-black py-3 inline-flex justify-center items-center gap-2"><ShoppingBag size={18}/>{busy?t('addingBtn'):t('addToCartBtn')}</button></div>{msg&&<div className="mt-4 rounded-xl bg-white/[.03] border border-white/10 p-3 text-sm flex gap-2">{!msg.includes('Error')&&<Check size={17} className="text-[#D4AF37]"/>}{msg}</div>}<Link href="/shop/cart" className="mt-4 inline-block text-[#D4AF37] font-bold">{t('goToCart')}</Link></section></div></div>
}
