'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { CalendarClock, CheckCircle2, ShieldCheck, Send, RefreshCw } from 'lucide-react'

type Props={tournaments:Array<{id:string;title:string;status:string}>}
export default function TournamentControlCenter({tournaments}:Props){
 const supabase=createClient(); const [tid,setTid]=useState(tournaments[0]?.id||''); const [slot,setSlot]=useState(30); const [rest,setRest]=useState(1); const [busy,setBusy]=useState(false); const [result,setResult]=useState<any>(null)
 async function run(fn:string){setBusy(true);setResult(null);const {data,error}=await supabase.rpc(fn,{p_tournament_id:tid,p_slot_minutes:slot,p_required_rest_slots:rest});setResult(error?{error:error.message}:{fn,data});setBusy(false)}
 return <section className="mt-8 rounded-3xl border border-white/10 bg-[#141B2D] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs tracking-[.25em] text-[#FFD700] font-black">TOURNAMENT INTELLIGENCE</div><h2 className="text-2xl font-black mt-1">CENTRO DE OPERACIONES</h2><p className="text-sm text-white/45 mt-2 max-w-2xl">Previsualiza, valida y publica programación con las restricciones reales de Dynasty. El motor puede bloquear una publicación cuando detecta conflictos.</p></div><ShieldCheck className="text-[#00F0FF]"/></div><div className="grid md:grid-cols-[1fr_120px_120px] gap-3 mt-5"><select value={tid} onChange={e=>setTid(e.target.value)} className="bg-[#0B0F19] border border-white/10 rounded-xl p-3 text-sm"><option value="">Selecciona torneo</option>{tournaments.map(t=><option key={t.id} value={t.id}>{t.title} · {t.status}</option>)}</select><input type="number" min="5" value={slot} onChange={e=>setSlot(Math.max(5,Number(e.target.value)||30))} className="bg-[#0B0F19] border border-white/10 rounded-xl p-3 text-sm" aria-label="slot minutes"/><input type="number" min="0" value={rest} onChange={e=>setRest(Math.max(0,Number(e.target.value)||0))} className="bg-[#0B0F19] border border-white/10 rounded-xl p-3 text-sm" aria-label="required rest slots"/></div><div className="grid md:grid-cols-3 gap-3 mt-3"><button disabled={busy||!tid} onClick={()=>run('preview_tournament_schedule')} className="rounded-xl border border-white/10 p-3 font-black inline-flex items-center justify-center gap-2"><CalendarClock size={16}/> PREVIEW</button><button disabled={busy||!tid} onClick={()=>run('validate_tournament_schedule')} className="rounded-xl border border-white/10 p-3 font-black inline-flex items-center justify-center gap-2"><CheckCircle2 size={16}/> VALIDAR</button><button disabled={busy||!tid} onClick={()=>run('publish_tournament_schedule')} className="rounded-xl bg-[#FFD700] text-black p-3 font-black inline-flex items-center justify-center gap-2"><Send size={16}/> PUBLICAR</button></div>{result&&<div className="mt-4 rounded-2xl bg-[#0B0F19] border border-white/10 p-4"><div className="flex items-center gap-2 text-sm font-black"><RefreshCw size={15}/> Resultado del motor</div><pre className="mt-3 text-xs text-white/55 whitespace-pre-wrap overflow-auto max-h-80">{JSON.stringify(result,null,2)}</pre></div>}</section>
}
