import Sidebar from '@/components/Sidebar'
import { Search, ShieldCheck, ShoppingBag, Tag, PackageCheck } from 'lucide-react'

const items = [
  ['Palas', 'Compra y vende equipamiento deportivo', 'Encuentra palas, accesorios y más dentro de la comunidad.'],
  ['Ropa', 'Estilo para competir', 'Jerseys, camisetas y equipación deportiva.'],
  ['Accesorios', 'Todo lo que completa tu juego', 'Bolsos, grips, pelotas y productos de entrenamiento.'],
]

export default function MarketplacePage(){
  return <main className="min-h-screen bg-[#0B0F19] text-white grid-bg"><Sidebar/><section className="lg:pl-64 p-6 lg:p-12 max-w-[1500px] mx-auto"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6 mb-10"><div><div className="text-[#00F0FF] text-xs font-black tracking-[.28em] uppercase">Comunidad · Compra · Venta</div><h1 className="text-4xl md:text-6xl font-black tracking-tight mt-2">Marketplace</h1><p className="text-white/50 mt-3 max-w-2xl">El mercado deportivo de CHALLENGE DYNASTY. Descubre productos, publica lo que ya no usas y conecta con compradores de la comunidad.</p></div><a href="/shop" className="rounded-2xl bg-[#00F0FF] text-black font-black px-6 py-3 inline-flex items-center justify-center gap-2"><ShoppingBag size={18}/> IR A DYNASTY SHOP</a></div><div className="rounded-2xl border border-white/10 bg-[#141B2D]/80 p-4 flex items-center gap-3 mb-8"><Search className="text-white/40" size={20}/><span className="text-white/40">Buscar productos, palas, ropa, accesorios...</span></div><div className="grid md:grid-cols-3 gap-5">{items.map(([name,title,desc],i)=><article key={name} className="rounded-3xl border border-white/10 bg-[#141B2D] p-7 min-h-56 flex flex-col"><div className="w-11 h-11 rounded-2xl bg-[#00F0FF]/10 text-[#00F0FF] grid place-items-center mb-6">{i===0?<Tag/>:i===1?<ShoppingBag/>:<PackageCheck/>}</div><div className="text-xs text-[#FFD700] font-black uppercase tracking-widest">{name}</div><h2 className="text-xl font-black mt-2">{title}</h2><p className="text-white/50 text-sm mt-3">{desc}</p><button className="mt-auto pt-6 text-left text-[#00F0FF] font-bold">Explorar categoría →</button></article>)}</div><div className="mt-8 rounded-3xl border border-dashed border-white/15 bg-white/[.02] p-8 text-center"><ShieldCheck className="mx-auto text-[#00F0FF] mb-3"/><h2 className="font-black text-xl">Marketplace en expansión</h2><p className="text-white/45 mt-2">La estructura ya está integrada para seguir conectando publicaciones, inventario y vendedores con Supabase.</p></div></section></main>}
