import Sidebar from '@/components/Sidebar'
import { Crown, ShoppingBag, Shirt, Sparkles, ArrowRight } from 'lucide-react'

const products = [
  ['DYNASTY Jersey', 'La camiseta oficial para competir con identidad.', 'Edición Performance'],
  ['DYNASTY Black', 'Diseño premium minimalista en negro y dorado.', 'Edición Signature'],
  ['DYNASTY Essentials', 'Prendas y accesorios para llevar la marca fuera de la cancha.', 'Lifestyle'],
]

export default function ShopPage(){
 return <main className="min-h-screen bg-[#0B0F19] text-white grid-bg"><Sidebar/><section className="lg:pl-64 p-6 lg:p-12 max-w-[1500px] mx-auto"><div className="rounded-[2rem] border border-[#FFD700]/20 bg-gradient-to-br from-[#1B1A12] via-[#141B2D] to-[#0B0F19] p-8 md:p-14 overflow-hidden relative"><Crown className="absolute right-8 top-8 text-[#FFD700]/20" size={140}/><div className="relative max-w-3xl"><div className="text-[#FFD700] text-xs font-black tracking-[.3em] uppercase">Official store</div><h1 className="text-5xl md:text-7xl font-black mt-3">DYNASTY <span className="text-[#FFD700]">SHOP</span></h1><p className="text-white/60 text-lg mt-5">La tienda oficial de la dinastía. Equipación, ropa y productos diseñados para quienes compiten, representan y dejan legado.</p><div className="flex flex-wrap gap-3 mt-8"><button className="rounded-2xl bg-[#FFD700] text-black font-black px-6 py-3 inline-flex items-center gap-2"><ShoppingBag size={18}/> VER COLECCIÓN</button><a href="/marketplace" className="rounded-2xl border border-white/15 px-6 py-3 font-bold">Marketplace</a></div></div></div><div className="flex items-center justify-between mt-10 mb-5"><div><div className="text-[#00F0FF] text-xs font-black tracking-[.25em] uppercase">Drop 01</div><h2 className="text-3xl font-black mt-1">Colección Dynasty</h2></div><Sparkles className="text-[#FFD700]"/></div><div className="grid md:grid-cols-3 gap-5">{products.map(([name,desc,tag],i)=><article key={name} className="rounded-3xl border border-white/10 bg-[#141B2D] overflow-hidden"><div className="aspect-[4/3] bg-gradient-to-br from-white/10 to-transparent grid place-items-center"><Shirt size={70} className={i===1?'text-[#FFD700]':'text-[#00F0FF]'}/></div><div className="p-6"><div className="text-xs text-white/40 uppercase tracking-widest">{tag}</div><h3 className="text-xl font-black mt-2">{name}</h3><p className="text-white/50 text-sm mt-2">{desc}</p><button className="mt-5 text-[#00F0FF] font-bold inline-flex items-center gap-1">Próximamente <ArrowRight size={16}/></button></div></article>)}</div></section></main>}
