import { Users, Trophy, ShieldCheck } from 'lucide-react'
import Sidebar from '@/components/Sidebar'
import BottomNav from '@/components/BottomNav'
import { createClient } from '@/lib/supabase/server'

export default async function Partners(){
 const supabase=createClient()
 const {data:sport}=await supabase.from('sports').select('id,name').eq('slug','padel').maybeSingle()
 const {data:{user}}=await supabase.auth.getUser()
 const {data:mySport}=user&&sport?await supabase.from('player_sports').select('skill_level').eq('profile_id',user.id).eq('sport_id',sport.id).maybeSingle():{data:null}
 const {data:ps}=sport?await supabase.from('player_sports').select('profile_id,skill_level').eq('sport_id',sport.id).eq('is_discoverable',true).limit(30):{data:[]}
 const ids=(ps??[]).map((x:any)=>x.profile_id).filter((id:string)=>id!==user?.id)
 const {data:profiles}=ids.length?await supabase.from('profiles').select('id,username,display_name,city').in('id',ids).eq('is_discoverable',true):{data:[]}
 const byId=new Map<string, any>((ps??[] as any[]).map((x:any)=>[x.profile_id,x]))
 return <div className="min-h-screen bg-[#0B0F19] grid-bg text-white"><Sidebar/><main className="lg:pl-64 pb-20 lg:pb-8"><div className="max-w-6xl mx-auto px-4 md:px-8 py-8"><div><div className="text-xs tracking-[.3em] text-[#00F0FF] font-black">PADEL · PARTNERS</div><h1 className="text-4xl md:text-5xl font-black mt-2">Encuentra tu pareja.</h1><p className="text-white/55 mt-3 max-w-2xl">Descubre jugadores configurados para pádel. Las invitaciones de partner aún no tienen un contrato backend oficial, por eso esta pantalla no simula solicitudes.</p></div><section className="mt-8"><div className="flex items-center justify-between mb-4"><h2 className="text-xl font-black">🎯 JUGADORES COMPATIBLES</h2><span className="text-xs text-white/40">{profiles?.length??0} disponibles</span></div><div className="grid md:grid-cols-3 gap-5">{(profiles??[]).map((p:any)=>{const sp=byId.get(p.id);return <article key={p.id} className="rounded-3xl border border-white/10 bg-[#141B2D] p-5 hover:border-[#00F0FF]/40 transition"><div className="text-xs text-[#00E676] font-black">{sp?.skill_level??'NIVEL NO INDICADO'}</div><div className="font-black text-xl mt-2">{p.display_name??p.username}</div><div className="text-xs text-white/40 mt-1">@{p.username} · {p.city??'Sin ciudad'}</div><div className="mt-4 flex gap-2"><a href={`/challenge/new?player=${p.id}&sport=${sport?.id??''}`} className="flex-1 rounded-xl bg-[#00F0FF] text-black px-4 py-3 text-xs font-black text-center">RETAR</a><a href={`/u/${p.username}`} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black">VER</a></div></article>})}{(profiles??[]).length===0&&<div className="md:col-span-3 rounded-3xl border border-white/10 bg-[#141B2D] p-8 text-center text-white/45">Configura Pádel en tu perfil para empezar a encontrar partners.</div>}</div></section><section className="grid md:grid-cols-3 gap-4 mt-8"><div className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><Users className="text-[#00F0FF]"/><h3 className="font-black text-lg mt-3">Pasaporte deportivo</h3><p className="text-sm text-white/45 mt-1">Tu nivel actual: {mySport?.skill_level??'sin configurar'}.</p></div><div className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><Trophy className="text-[#FFD700]"/><h3 className="font-black text-lg mt-3">Reto directo</h3><p className="text-sm text-white/45 mt-1">Puedes convertir cualquier perfil compatible en un reto oficial.</p></div><div className="rounded-3xl border border-white/10 bg-[#141B2D] p-5"><ShieldCheck className="text-[#00E676]"/><h3 className="font-black text-lg mt-3">Sin datos ficticios</h3><p className="text-sm text-white/45 mt-1">La pantalla solo muestra perfiles existentes y descubribles.</p></div></section></div></main><BottomNav/></div>
}
